### PR TITLE
Changed VR.VRSettings to XR.XRSettings

### PR DESCRIPTION
**Pull request by Ahrdie**
Fixing the warning dialogue and Unitys autofix for the Change from `VR.VRSettings` to `XR.XRSettings`.

### CODE REVIEW

**Comment by kisak-valve** [comment]
When was this change in Unity? Can the adjustment be done without causing trouble for older Unity versions?

**Comment by bddckr** [comment]
This should work fine (we're doing this in VRTK):
```csharp
#if UNITY_2017_2_OR_NEWER
    using UnityEngine.XR;
#else
    using XRSettings = UnityEngine.VR.VRSettings;
    using XRDevice = UnityEngine.VR.VRDevice;
#endif
```
Add this to the top of the file in the using section and then in the same file use `XRSettings` or `XRDevice` instead and it will work for all versions in this case (the used API seems to be compatible).

**Comment by davegreco** [comment]
When can we expect some of these things to get merged in for a new version? There have been great changes in the past 6 months and people have been proactive about about providing solutions but it's getting to be a bit of a list. Who's in charge of this stuff, what are the plans for this system I'm hoping to see Valve continue to be the go to lightweight interchange for this open VR world but I'm a bit concerned that despite the efforts from the community here in order to use this in modern versions of Unity you're essentially having to branch and monkey batch a bunch of pending PRs, this shouldn't require much of someones time to maintain (though I understand time is always lacking).

**Comment by davegreco** [comment]
By the way, this is no longer a warning. Unless I'm missing some build setting to ignore it.

> Error	CS0619	'VRDevice' is obsolete: 'VRDevice has been moved and renamed.  Use UnityEngine.XR.XRDevice instead (UnityUpgradable) -> UnityEngine.XR.XRDevice'

**Comment by bddckr** [comment]
@davegreco Unity should ask you to run the API Updater on the imported SteamVR asset when you do so. If you allow/confirm that it will fix these for you automatically.

**Comment by zite** [comment]
Thanks Bddckr. Added this in version 2.0.

**Pull request closed without merging**
