### PR TITLE
Fix controller jittering while Player parent moving at high speed

### PR DESCRIPTION
**Pull request by Team-on**
Brutforce fix, so I not sure is it broke anything else. Anyway hands and interactable in hand not jitter anymore

### CODE REVIEW

**Comment by troyspencer** [comment]
This fixes #593 ?

**Comment by Team-on** [comment]
You can give a try. As you can see I just set position, instead of physics based moving, so controller speed no more clamped due to physics settings

**Comment by montoulieu** [comment]
This is working perfectly for me. Not sure if any regressions are caused by this but I appreciate the fix!

**Comment by montoulieu** [comment]
You also appear to be calling FixedUpdate() in Update() on the Hand.cs file which would call everything in FixedUpdate 50 times every frame.

**Comment by zite** [comment]
Additions to the interaction system are out of scope of this project at this point. Thanks for the contribution though.

**Pull request closed without merging**
